# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/seans/dotfiles/submodules/lastpass-cli

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/seans/dotfiles/submodules/lastpass-cli

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seans/dotfiles/submodules/lastpass-cli/CMakeFiles /home/seans/dotfiles/submodules/lastpass-cli//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seans/dotfiles/submodules/lastpass-cli/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lpass

# Build rule for target.
lpass: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lpass
.PHONY : lpass

# fast build rule for target.
lpass/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/build
.PHONY : lpass/fast

#=============================================================================
# Target rules for targets named lpass-test

# Build rule for target.
lpass-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lpass-test
.PHONY : lpass-test

# fast build rule for target.
lpass-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/build
.PHONY : lpass-test/fast

#=============================================================================
# Target rules for targets named doc-man

# Build rule for target.
doc-man: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc-man
.PHONY : doc-man

# fast build rule for target.
doc-man/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/doc-man.dir/build.make CMakeFiles/doc-man.dir/build
.PHONY : doc-man/fast

#=============================================================================
# Target rules for targets named doc-html

# Build rule for target.
doc-html: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc-html
.PHONY : doc-html

# fast build rule for target.
doc-html/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/doc-html.dir/build.make CMakeFiles/doc-html.dir/build
.PHONY : doc-html/fast

#=============================================================================
# Target rules for targets named install-doc

# Build rule for target.
install-doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 install-doc
.PHONY : install-doc

# fast build rule for target.
install-doc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/install-doc.dir/build.make CMakeFiles/install-doc.dir/build
.PHONY : install-doc/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

agent.o: agent.c.o
.PHONY : agent.o

# target to build an object file
agent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/agent.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/agent.c.o
.PHONY : agent.c.o

agent.i: agent.c.i
.PHONY : agent.i

# target to preprocess a source file
agent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/agent.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/agent.c.i
.PHONY : agent.c.i

agent.s: agent.c.s
.PHONY : agent.s

# target to generate assembly for a file
agent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/agent.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/agent.c.s
.PHONY : agent.c.s

blob.o: blob.c.o
.PHONY : blob.o

# target to build an object file
blob.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/blob.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/blob.c.o
.PHONY : blob.c.o

blob.i: blob.c.i
.PHONY : blob.i

# target to preprocess a source file
blob.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/blob.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/blob.c.i
.PHONY : blob.c.i

blob.s: blob.c.s
.PHONY : blob.s

# target to generate assembly for a file
blob.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/blob.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/blob.c.s
.PHONY : blob.c.s

cipher.o: cipher.c.o
.PHONY : cipher.o

# target to build an object file
cipher.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cipher.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cipher.c.o
.PHONY : cipher.c.o

cipher.i: cipher.c.i
.PHONY : cipher.i

# target to preprocess a source file
cipher.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cipher.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cipher.c.i
.PHONY : cipher.c.i

cipher.s: cipher.c.s
.PHONY : cipher.s

# target to generate assembly for a file
cipher.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cipher.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cipher.c.s
.PHONY : cipher.c.s

clipboard.o: clipboard.c.o
.PHONY : clipboard.o

# target to build an object file
clipboard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/clipboard.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/clipboard.c.o
.PHONY : clipboard.c.o

clipboard.i: clipboard.c.i
.PHONY : clipboard.i

# target to preprocess a source file
clipboard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/clipboard.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/clipboard.c.i
.PHONY : clipboard.c.i

clipboard.s: clipboard.c.s
.PHONY : clipboard.s

# target to generate assembly for a file
clipboard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/clipboard.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/clipboard.c.s
.PHONY : clipboard.c.s

cmd-add.o: cmd-add.c.o
.PHONY : cmd-add.o

# target to build an object file
cmd-add.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-add.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-add.c.o
.PHONY : cmd-add.c.o

cmd-add.i: cmd-add.c.i
.PHONY : cmd-add.i

# target to preprocess a source file
cmd-add.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-add.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-add.c.i
.PHONY : cmd-add.c.i

cmd-add.s: cmd-add.c.s
.PHONY : cmd-add.s

# target to generate assembly for a file
cmd-add.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-add.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-add.c.s
.PHONY : cmd-add.c.s

cmd-duplicate.o: cmd-duplicate.c.o
.PHONY : cmd-duplicate.o

# target to build an object file
cmd-duplicate.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-duplicate.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-duplicate.c.o
.PHONY : cmd-duplicate.c.o

cmd-duplicate.i: cmd-duplicate.c.i
.PHONY : cmd-duplicate.i

# target to preprocess a source file
cmd-duplicate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-duplicate.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-duplicate.c.i
.PHONY : cmd-duplicate.c.i

cmd-duplicate.s: cmd-duplicate.c.s
.PHONY : cmd-duplicate.s

# target to generate assembly for a file
cmd-duplicate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-duplicate.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-duplicate.c.s
.PHONY : cmd-duplicate.c.s

cmd-edit.o: cmd-edit.c.o
.PHONY : cmd-edit.o

# target to build an object file
cmd-edit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-edit.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-edit.c.o
.PHONY : cmd-edit.c.o

cmd-edit.i: cmd-edit.c.i
.PHONY : cmd-edit.i

# target to preprocess a source file
cmd-edit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-edit.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-edit.c.i
.PHONY : cmd-edit.c.i

cmd-edit.s: cmd-edit.c.s
.PHONY : cmd-edit.s

# target to generate assembly for a file
cmd-edit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-edit.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-edit.c.s
.PHONY : cmd-edit.c.s

cmd-export.o: cmd-export.c.o
.PHONY : cmd-export.o

# target to build an object file
cmd-export.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-export.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-export.c.o
.PHONY : cmd-export.c.o

cmd-export.i: cmd-export.c.i
.PHONY : cmd-export.i

# target to preprocess a source file
cmd-export.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-export.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-export.c.i
.PHONY : cmd-export.c.i

cmd-export.s: cmd-export.c.s
.PHONY : cmd-export.s

# target to generate assembly for a file
cmd-export.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-export.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-export.c.s
.PHONY : cmd-export.c.s

cmd-generate.o: cmd-generate.c.o
.PHONY : cmd-generate.o

# target to build an object file
cmd-generate.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-generate.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-generate.c.o
.PHONY : cmd-generate.c.o

cmd-generate.i: cmd-generate.c.i
.PHONY : cmd-generate.i

# target to preprocess a source file
cmd-generate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-generate.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-generate.c.i
.PHONY : cmd-generate.c.i

cmd-generate.s: cmd-generate.c.s
.PHONY : cmd-generate.s

# target to generate assembly for a file
cmd-generate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-generate.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-generate.c.s
.PHONY : cmd-generate.c.s

cmd-import.o: cmd-import.c.o
.PHONY : cmd-import.o

# target to build an object file
cmd-import.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-import.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-import.c.o
.PHONY : cmd-import.c.o

cmd-import.i: cmd-import.c.i
.PHONY : cmd-import.i

# target to preprocess a source file
cmd-import.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-import.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-import.c.i
.PHONY : cmd-import.c.i

cmd-import.s: cmd-import.c.s
.PHONY : cmd-import.s

# target to generate assembly for a file
cmd-import.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-import.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-import.c.s
.PHONY : cmd-import.c.s

cmd-login.o: cmd-login.c.o
.PHONY : cmd-login.o

# target to build an object file
cmd-login.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-login.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-login.c.o
.PHONY : cmd-login.c.o

cmd-login.i: cmd-login.c.i
.PHONY : cmd-login.i

# target to preprocess a source file
cmd-login.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-login.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-login.c.i
.PHONY : cmd-login.c.i

cmd-login.s: cmd-login.c.s
.PHONY : cmd-login.s

# target to generate assembly for a file
cmd-login.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-login.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-login.c.s
.PHONY : cmd-login.c.s

cmd-logout.o: cmd-logout.c.o
.PHONY : cmd-logout.o

# target to build an object file
cmd-logout.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-logout.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-logout.c.o
.PHONY : cmd-logout.c.o

cmd-logout.i: cmd-logout.c.i
.PHONY : cmd-logout.i

# target to preprocess a source file
cmd-logout.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-logout.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-logout.c.i
.PHONY : cmd-logout.c.i

cmd-logout.s: cmd-logout.c.s
.PHONY : cmd-logout.s

# target to generate assembly for a file
cmd-logout.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-logout.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-logout.c.s
.PHONY : cmd-logout.c.s

cmd-ls.o: cmd-ls.c.o
.PHONY : cmd-ls.o

# target to build an object file
cmd-ls.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-ls.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-ls.c.o
.PHONY : cmd-ls.c.o

cmd-ls.i: cmd-ls.c.i
.PHONY : cmd-ls.i

# target to preprocess a source file
cmd-ls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-ls.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-ls.c.i
.PHONY : cmd-ls.c.i

cmd-ls.s: cmd-ls.c.s
.PHONY : cmd-ls.s

# target to generate assembly for a file
cmd-ls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-ls.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-ls.c.s
.PHONY : cmd-ls.c.s

cmd-mv.o: cmd-mv.c.o
.PHONY : cmd-mv.o

# target to build an object file
cmd-mv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-mv.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-mv.c.o
.PHONY : cmd-mv.c.o

cmd-mv.i: cmd-mv.c.i
.PHONY : cmd-mv.i

# target to preprocess a source file
cmd-mv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-mv.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-mv.c.i
.PHONY : cmd-mv.c.i

cmd-mv.s: cmd-mv.c.s
.PHONY : cmd-mv.s

# target to generate assembly for a file
cmd-mv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-mv.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-mv.c.s
.PHONY : cmd-mv.c.s

cmd-passwd.o: cmd-passwd.c.o
.PHONY : cmd-passwd.o

# target to build an object file
cmd-passwd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-passwd.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-passwd.c.o
.PHONY : cmd-passwd.c.o

cmd-passwd.i: cmd-passwd.c.i
.PHONY : cmd-passwd.i

# target to preprocess a source file
cmd-passwd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-passwd.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-passwd.c.i
.PHONY : cmd-passwd.c.i

cmd-passwd.s: cmd-passwd.c.s
.PHONY : cmd-passwd.s

# target to generate assembly for a file
cmd-passwd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-passwd.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-passwd.c.s
.PHONY : cmd-passwd.c.s

cmd-rm.o: cmd-rm.c.o
.PHONY : cmd-rm.o

# target to build an object file
cmd-rm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-rm.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-rm.c.o
.PHONY : cmd-rm.c.o

cmd-rm.i: cmd-rm.c.i
.PHONY : cmd-rm.i

# target to preprocess a source file
cmd-rm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-rm.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-rm.c.i
.PHONY : cmd-rm.c.i

cmd-rm.s: cmd-rm.c.s
.PHONY : cmd-rm.s

# target to generate assembly for a file
cmd-rm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-rm.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-rm.c.s
.PHONY : cmd-rm.c.s

cmd-share.o: cmd-share.c.o
.PHONY : cmd-share.o

# target to build an object file
cmd-share.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-share.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-share.c.o
.PHONY : cmd-share.c.o

cmd-share.i: cmd-share.c.i
.PHONY : cmd-share.i

# target to preprocess a source file
cmd-share.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-share.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-share.c.i
.PHONY : cmd-share.c.i

cmd-share.s: cmd-share.c.s
.PHONY : cmd-share.s

# target to generate assembly for a file
cmd-share.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-share.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-share.c.s
.PHONY : cmd-share.c.s

cmd-show.o: cmd-show.c.o
.PHONY : cmd-show.o

# target to build an object file
cmd-show.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-show.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-show.c.o
.PHONY : cmd-show.c.o

cmd-show.i: cmd-show.c.i
.PHONY : cmd-show.i

# target to preprocess a source file
cmd-show.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-show.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-show.c.i
.PHONY : cmd-show.c.i

cmd-show.s: cmd-show.c.s
.PHONY : cmd-show.s

# target to generate assembly for a file
cmd-show.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-show.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-show.c.s
.PHONY : cmd-show.c.s

cmd-status.o: cmd-status.c.o
.PHONY : cmd-status.o

# target to build an object file
cmd-status.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-status.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-status.c.o
.PHONY : cmd-status.c.o

cmd-status.i: cmd-status.c.i
.PHONY : cmd-status.i

# target to preprocess a source file
cmd-status.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-status.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-status.c.i
.PHONY : cmd-status.c.i

cmd-status.s: cmd-status.c.s
.PHONY : cmd-status.s

# target to generate assembly for a file
cmd-status.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-status.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-status.c.s
.PHONY : cmd-status.c.s

cmd-sync.o: cmd-sync.c.o
.PHONY : cmd-sync.o

# target to build an object file
cmd-sync.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-sync.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-sync.c.o
.PHONY : cmd-sync.c.o

cmd-sync.i: cmd-sync.c.i
.PHONY : cmd-sync.i

# target to preprocess a source file
cmd-sync.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-sync.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-sync.c.i
.PHONY : cmd-sync.c.i

cmd-sync.s: cmd-sync.c.s
.PHONY : cmd-sync.s

# target to generate assembly for a file
cmd-sync.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd-sync.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd-sync.c.s
.PHONY : cmd-sync.c.s

cmd.o: cmd.c.o
.PHONY : cmd.o

# target to build an object file
cmd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd.c.o
.PHONY : cmd.c.o

cmd.i: cmd.c.i
.PHONY : cmd.i

# target to preprocess a source file
cmd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd.c.i
.PHONY : cmd.c.i

cmd.s: cmd.c.s
.PHONY : cmd.s

# target to generate assembly for a file
cmd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/cmd.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/cmd.c.s
.PHONY : cmd.c.s

config.o: config.c.o
.PHONY : config.o

# target to build an object file
config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/config.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/config.c.o
.PHONY : config.c.o

config.i: config.c.i
.PHONY : config.i

# target to preprocess a source file
config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/config.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/config.c.i
.PHONY : config.c.i

config.s: config.c.s
.PHONY : config.s

# target to generate assembly for a file
config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/config.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/config.c.s
.PHONY : config.c.s

edit.o: edit.c.o
.PHONY : edit.o

# target to build an object file
edit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/edit.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/edit.c.o
.PHONY : edit.c.o

edit.i: edit.c.i
.PHONY : edit.i

# target to preprocess a source file
edit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/edit.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/edit.c.i
.PHONY : edit.c.i

edit.s: edit.c.s
.PHONY : edit.s

# target to generate assembly for a file
edit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/edit.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/edit.c.s
.PHONY : edit.c.s

endpoints-login.o: endpoints-login.c.o
.PHONY : endpoints-login.o

# target to build an object file
endpoints-login.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/endpoints-login.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/endpoints-login.c.o
.PHONY : endpoints-login.c.o

endpoints-login.i: endpoints-login.c.i
.PHONY : endpoints-login.i

# target to preprocess a source file
endpoints-login.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/endpoints-login.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/endpoints-login.c.i
.PHONY : endpoints-login.c.i

endpoints-login.s: endpoints-login.c.s
.PHONY : endpoints-login.s

# target to generate assembly for a file
endpoints-login.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/endpoints-login.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/endpoints-login.c.s
.PHONY : endpoints-login.c.s

endpoints-share.o: endpoints-share.c.o
.PHONY : endpoints-share.o

# target to build an object file
endpoints-share.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/endpoints-share.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/endpoints-share.c.o
.PHONY : endpoints-share.c.o

endpoints-share.i: endpoints-share.c.i
.PHONY : endpoints-share.i

# target to preprocess a source file
endpoints-share.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/endpoints-share.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/endpoints-share.c.i
.PHONY : endpoints-share.c.i

endpoints-share.s: endpoints-share.c.s
.PHONY : endpoints-share.s

# target to generate assembly for a file
endpoints-share.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/endpoints-share.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/endpoints-share.c.s
.PHONY : endpoints-share.c.s

endpoints.o: endpoints.c.o
.PHONY : endpoints.o

# target to build an object file
endpoints.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/endpoints.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/endpoints.c.o
.PHONY : endpoints.c.o

endpoints.i: endpoints.c.i
.PHONY : endpoints.i

# target to preprocess a source file
endpoints.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/endpoints.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/endpoints.c.i
.PHONY : endpoints.c.i

endpoints.s: endpoints.c.s
.PHONY : endpoints.s

# target to generate assembly for a file
endpoints.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/endpoints.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/endpoints.c.s
.PHONY : endpoints.c.s

format.o: format.c.o
.PHONY : format.o

# target to build an object file
format.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/format.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/format.c.o
.PHONY : format.c.o

format.i: format.c.i
.PHONY : format.i

# target to preprocess a source file
format.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/format.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/format.c.i
.PHONY : format.c.i

format.s: format.c.s
.PHONY : format.s

# target to generate assembly for a file
format.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/format.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/format.c.s
.PHONY : format.c.s

http.o: http.c.o
.PHONY : http.o

# target to build an object file
http.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/http.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/http.c.o
.PHONY : http.c.o

http.i: http.c.i
.PHONY : http.i

# target to preprocess a source file
http.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/http.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/http.c.i
.PHONY : http.c.i

http.s: http.c.s
.PHONY : http.s

# target to generate assembly for a file
http.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/http.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/http.c.s
.PHONY : http.c.s

json-format.o: json-format.c.o
.PHONY : json-format.o

# target to build an object file
json-format.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/json-format.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/json-format.c.o
.PHONY : json-format.c.o

json-format.i: json-format.c.i
.PHONY : json-format.i

# target to preprocess a source file
json-format.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/json-format.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/json-format.c.i
.PHONY : json-format.c.i

json-format.s: json-format.c.s
.PHONY : json-format.s

# target to generate assembly for a file
json-format.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/json-format.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/json-format.c.s
.PHONY : json-format.c.s

kdf.o: kdf.c.o
.PHONY : kdf.o

# target to build an object file
kdf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/kdf.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/kdf.c.o
.PHONY : kdf.c.o

kdf.i: kdf.c.i
.PHONY : kdf.i

# target to preprocess a source file
kdf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/kdf.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/kdf.c.i
.PHONY : kdf.c.i

kdf.s: kdf.c.s
.PHONY : kdf.s

# target to generate assembly for a file
kdf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/kdf.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/kdf.c.s
.PHONY : kdf.c.s

log.o: log.c.o
.PHONY : log.o

# target to build an object file
log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/log.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/log.c.o
.PHONY : log.c.o

log.i: log.c.i
.PHONY : log.i

# target to preprocess a source file
log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/log.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/log.c.i
.PHONY : log.c.i

log.s: log.c.s
.PHONY : log.s

# target to generate assembly for a file
log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/log.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/log.c.s
.PHONY : log.c.s

lpass.o: lpass.c.o
.PHONY : lpass.o

# target to build an object file
lpass.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/lpass.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/lpass.c.o
.PHONY : lpass.c.o

lpass.i: lpass.c.i
.PHONY : lpass.i

# target to preprocess a source file
lpass.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/lpass.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/lpass.c.i
.PHONY : lpass.c.i

lpass.s: lpass.c.s
.PHONY : lpass.s

# target to generate assembly for a file
lpass.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/lpass.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/lpass.c.s
.PHONY : lpass.c.s

notes.o: notes.c.o
.PHONY : notes.o

# target to build an object file
notes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/notes.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/notes.c.o
.PHONY : notes.c.o

notes.i: notes.c.i
.PHONY : notes.i

# target to preprocess a source file
notes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/notes.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/notes.c.i
.PHONY : notes.c.i

notes.s: notes.c.s
.PHONY : notes.s

# target to generate assembly for a file
notes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/notes.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/notes.c.s
.PHONY : notes.c.s

password.o: password.c.o
.PHONY : password.o

# target to build an object file
password.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/password.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/password.c.o
.PHONY : password.c.o

password.i: password.c.i
.PHONY : password.i

# target to preprocess a source file
password.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/password.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/password.c.i
.PHONY : password.c.i

password.s: password.c.s
.PHONY : password.s

# target to generate assembly for a file
password.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/password.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/password.c.s
.PHONY : password.c.s

pbkdf2.o: pbkdf2.c.o
.PHONY : pbkdf2.o

# target to build an object file
pbkdf2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/pbkdf2.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/pbkdf2.c.o
.PHONY : pbkdf2.c.o

pbkdf2.i: pbkdf2.c.i
.PHONY : pbkdf2.i

# target to preprocess a source file
pbkdf2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/pbkdf2.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/pbkdf2.c.i
.PHONY : pbkdf2.c.i

pbkdf2.s: pbkdf2.c.s
.PHONY : pbkdf2.s

# target to generate assembly for a file
pbkdf2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/pbkdf2.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/pbkdf2.c.s
.PHONY : pbkdf2.c.s

process.o: process.c.o
.PHONY : process.o

# target to build an object file
process.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/process.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/process.c.o
.PHONY : process.c.o

process.i: process.c.i
.PHONY : process.i

# target to preprocess a source file
process.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/process.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/process.c.i
.PHONY : process.c.i

process.s: process.c.s
.PHONY : process.s

# target to generate assembly for a file
process.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/process.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/process.c.s
.PHONY : process.c.s

session.o: session.c.o
.PHONY : session.o

# target to build an object file
session.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/session.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/session.c.o
.PHONY : session.c.o

session.i: session.c.i
.PHONY : session.i

# target to preprocess a source file
session.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/session.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/session.c.i
.PHONY : session.c.i

session.s: session.c.s
.PHONY : session.s

# target to generate assembly for a file
session.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/session.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/session.c.s
.PHONY : session.c.s

terminal.o: terminal.c.o
.PHONY : terminal.o

# target to build an object file
terminal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/terminal.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/terminal.c.o
.PHONY : terminal.c.o

terminal.i: terminal.c.i
.PHONY : terminal.i

# target to preprocess a source file
terminal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/terminal.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/terminal.c.i
.PHONY : terminal.c.i

terminal.s: terminal.c.s
.PHONY : terminal.s

# target to generate assembly for a file
terminal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/terminal.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/terminal.c.s
.PHONY : terminal.c.s

test/http_mock.o: test/http_mock.c.o
.PHONY : test/http_mock.o

# target to build an object file
test/http_mock.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/test/http_mock.c.o
.PHONY : test/http_mock.c.o

test/http_mock.i: test/http_mock.c.i
.PHONY : test/http_mock.i

# target to preprocess a source file
test/http_mock.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/test/http_mock.c.i
.PHONY : test/http_mock.c.i

test/http_mock.s: test/http_mock.c.s
.PHONY : test/http_mock.s

# target to generate assembly for a file
test/http_mock.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/test/http_mock.c.s
.PHONY : test/http_mock.c.s

upload-queue.o: upload-queue.c.o
.PHONY : upload-queue.o

# target to build an object file
upload-queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/upload-queue.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/upload-queue.c.o
.PHONY : upload-queue.c.o

upload-queue.i: upload-queue.c.i
.PHONY : upload-queue.i

# target to preprocess a source file
upload-queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/upload-queue.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/upload-queue.c.i
.PHONY : upload-queue.c.i

upload-queue.s: upload-queue.c.s
.PHONY : upload-queue.s

# target to generate assembly for a file
upload-queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/upload-queue.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/upload-queue.c.s
.PHONY : upload-queue.c.s

util.o: util.c.o
.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/util.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/util.c.s
.PHONY : util.c.s

xml.o: xml.c.o
.PHONY : xml.o

# target to build an object file
xml.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/xml.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/xml.c.o
.PHONY : xml.c.o

xml.i: xml.c.i
.PHONY : xml.i

# target to preprocess a source file
xml.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/xml.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/xml.c.i
.PHONY : xml.c.i

xml.s: xml.c.s
.PHONY : xml.s

# target to generate assembly for a file
xml.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass.dir/build.make CMakeFiles/lpass.dir/xml.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpass-test.dir/build.make CMakeFiles/lpass-test.dir/xml.c.s
.PHONY : xml.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... doc-html"
	@echo "... doc-man"
	@echo "... install-doc"
	@echo "... uninstall"
	@echo "... lpass"
	@echo "... lpass-test"
	@echo "... agent.o"
	@echo "... agent.i"
	@echo "... agent.s"
	@echo "... blob.o"
	@echo "... blob.i"
	@echo "... blob.s"
	@echo "... cipher.o"
	@echo "... cipher.i"
	@echo "... cipher.s"
	@echo "... clipboard.o"
	@echo "... clipboard.i"
	@echo "... clipboard.s"
	@echo "... cmd-add.o"
	@echo "... cmd-add.i"
	@echo "... cmd-add.s"
	@echo "... cmd-duplicate.o"
	@echo "... cmd-duplicate.i"
	@echo "... cmd-duplicate.s"
	@echo "... cmd-edit.o"
	@echo "... cmd-edit.i"
	@echo "... cmd-edit.s"
	@echo "... cmd-export.o"
	@echo "... cmd-export.i"
	@echo "... cmd-export.s"
	@echo "... cmd-generate.o"
	@echo "... cmd-generate.i"
	@echo "... cmd-generate.s"
	@echo "... cmd-import.o"
	@echo "... cmd-import.i"
	@echo "... cmd-import.s"
	@echo "... cmd-login.o"
	@echo "... cmd-login.i"
	@echo "... cmd-login.s"
	@echo "... cmd-logout.o"
	@echo "... cmd-logout.i"
	@echo "... cmd-logout.s"
	@echo "... cmd-ls.o"
	@echo "... cmd-ls.i"
	@echo "... cmd-ls.s"
	@echo "... cmd-mv.o"
	@echo "... cmd-mv.i"
	@echo "... cmd-mv.s"
	@echo "... cmd-passwd.o"
	@echo "... cmd-passwd.i"
	@echo "... cmd-passwd.s"
	@echo "... cmd-rm.o"
	@echo "... cmd-rm.i"
	@echo "... cmd-rm.s"
	@echo "... cmd-share.o"
	@echo "... cmd-share.i"
	@echo "... cmd-share.s"
	@echo "... cmd-show.o"
	@echo "... cmd-show.i"
	@echo "... cmd-show.s"
	@echo "... cmd-status.o"
	@echo "... cmd-status.i"
	@echo "... cmd-status.s"
	@echo "... cmd-sync.o"
	@echo "... cmd-sync.i"
	@echo "... cmd-sync.s"
	@echo "... cmd.o"
	@echo "... cmd.i"
	@echo "... cmd.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... edit.o"
	@echo "... edit.i"
	@echo "... edit.s"
	@echo "... endpoints-login.o"
	@echo "... endpoints-login.i"
	@echo "... endpoints-login.s"
	@echo "... endpoints-share.o"
	@echo "... endpoints-share.i"
	@echo "... endpoints-share.s"
	@echo "... endpoints.o"
	@echo "... endpoints.i"
	@echo "... endpoints.s"
	@echo "... format.o"
	@echo "... format.i"
	@echo "... format.s"
	@echo "... http.o"
	@echo "... http.i"
	@echo "... http.s"
	@echo "... json-format.o"
	@echo "... json-format.i"
	@echo "... json-format.s"
	@echo "... kdf.o"
	@echo "... kdf.i"
	@echo "... kdf.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... lpass.o"
	@echo "... lpass.i"
	@echo "... lpass.s"
	@echo "... notes.o"
	@echo "... notes.i"
	@echo "... notes.s"
	@echo "... password.o"
	@echo "... password.i"
	@echo "... password.s"
	@echo "... pbkdf2.o"
	@echo "... pbkdf2.i"
	@echo "... pbkdf2.s"
	@echo "... process.o"
	@echo "... process.i"
	@echo "... process.s"
	@echo "... session.o"
	@echo "... session.i"
	@echo "... session.s"
	@echo "... terminal.o"
	@echo "... terminal.i"
	@echo "... terminal.s"
	@echo "... test/http_mock.o"
	@echo "... test/http_mock.i"
	@echo "... test/http_mock.s"
	@echo "... upload-queue.o"
	@echo "... upload-queue.i"
	@echo "... upload-queue.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... xml.o"
	@echo "... xml.i"
	@echo "... xml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

